### PR TITLE
Add a cartesian controller

### PR DESCRIPTION
**Pull request by dogoepp**
This trajectory generator (a.k.a. controller) is used by [`hexapod_ros/hexapod_driver`](https://github.com/resibots/hexapod_ros/tree/master/hexapod_driver), along with [`hexapod_ik`](https://github.com/resibots/hexapod_ik) to generate movements that are kinematically correct.

### CODE REVIEW

**Review by costashatz — COMMENTED** [review]
This PR is great! Thanks for making this effort!

One minor detail: why isn't it possible to have the broken legs functionality?

**Comment by dogoepp** [comment]
I think it is because that I don't see why the information about broken legs should be given so much upstream. Also, the way I wrote the inverse kinematics, the number of legs is fixed at compile time. This can be changed if you think it is needed.

**Comment by costashatz** [comment]
> I think it is because that I don't see why the information about broken legs should be given so much upstream. Also, the way I wrote the inverse kinematics, the number of legs is fixed at compile time. This can be changed if you think it is needed.

The main issue is that I have in my to-do list to replace `hexapod_dart` (and deprecate `hexapod_robdyn`) with an instance of the more generic `robot_dart` repo. I also found a way of creating removed legs without having to remove the joints (i.e., there's no need for these explicit functions like `set_broken_legs`). So, I would say it's ok to merge it like this and once I get to replacing `hexapod_dart` with `robot_dart`, we should open a new PR to remove all the broken leg functions. What do you think?

**Comment by dogoepp** [comment]
I love it !

**Comment by dogoepp** [comment]
Should I merge ?

**Comment by costashatz** [comment]
> Should I merge ?

Yeap!

**Pull request merged**
