### PR TITLE
Simple A* planner

### PR DESCRIPTION
**Pull request by costashatz**
**Simple A\* planner**
- A robot has a series of available actions (e.g. move forward, move backward, etc.)
- At first a graph is created using a user-specified max variable
- A\* is ran on the graph and the optimal path is returned
- If the goal cannot be reached (either because it is out of reach due to the max variable or because the actions are not as dense as they should), the goal is refined to the state closer to the actual goal.

It seems to work pretty good. Only issue is that creating the graph takes some time. But this is a very simple planner to make our experiments. Maybe we can improve it some time (if this planner is useful).

### CODE REVIEW

**Comment by jbmouret** [comment]
Why not http://www.boost.org/doc/libs/1_38_0/libs/graph/doc/astar_search.html ?

On 14 Dec 2015, at 21:01, Konstantinos Chatzilygeroudis notifications@github.com wrote:

> Simple A\* planner
> 
>   � A robot has a series of available actions (e.g. move forward, move backward, etc.)
>   � At first a graph is created using a user-specified max variable
>   � A\* is ran on the graph and the optimal path is returned
>   � If the goal cannot be reached (either because it is out of reach due to the max variable or because the actions are not as dense as they should), the goal is refined to the state closer to the actual goal.
> It seems to work pretty good. Only issue is that creating the graph takes some time. But this is a very simple planner to make our experiments. Maybe we can improve it some time (if this planner is useful).
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/resibots/hexapod_common/pull/1
> 
> Commit Summary
> 
>   � First A-star implementation
>   � Removed .clang-format
>   � Graphics made optional
>   � Updated READMEs
> File Changes
> 
>   � M README.md (6)
>   � A hexapod_planner/README.md (87)
>   � A hexapod_planner/eigen.py (31)
>   � A hexapod_planner/sfml.py (48)
>   � A hexapod_planner/src/hexapod_planner_simple.hpp (229)
>   � A hexapod_planner/src/simple_env.hpp (71)
>   � A hexapod_planner/src/state_simple.hpp (68)
>   � A hexapod_planner/src/test.cpp (251)
>   � A hexapod_planner/waf (170)
>   � A hexapod_planner/wscript (65)
> Patch Links:
> 
>   � https://github.com/resibots/hexapod_common/pull/1.patch
>   � https://github.com/resibots/hexapod_common/pull/1.diff
> �
> Reply to this email directly or view it on GitHub.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
Because:
- We do not need any extra dependency
- To code A\* search is super-easy
  - I used this pseudocode: https://en.wikipedia.org/wiki/A*_search_algorithm#Pseudocode
- Boost graph library is a little weird to program
- The most weird and most time consuming part is the creation of the graph, which we still have to do with the boost version of A*.

Although, I have to note that I could add improvements (e.g. storing structure for the graph).

**Comment by jbmouret** [comment]
OK. Thanks.

On 14 Dec 2015, at 22:15, Konstantinos Chatzilygeroudis notifications@github.com wrote:

> Because:
> 
>   � We do not need any extra dependency
>   � To code A\* search is super-easy
>       � I used this pseudocode: https://en.wikipedia.org/wiki/A*_search_algorithm#Pseudocode
>   � Boost graph library is a little weird to program
>   � The most weird and most time consuming part is the creation of the graph, which we still have to do with the boost version of A*.
> Although, I have to note that I could add improvements (e.g. storing structure for the graph).
> 
> �
> Reply to this email directly or view it on GitHub.

� Jean-Baptiste Mouret
http://pages.isir.upmc.fr/~mouret/

**Comment by costashatz** [comment]
Should we merge?

**Comment by jbmouret** [comment]
Yes

**Pull request merged**
